# Generated by Django 5.2.13 on 2026-06-15 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normaliser_identifiants(apps, schema_editor):
    """Met les email/telephone vides ('') à NULL pour éviter les collisions
    de contrainte d'unicité (plusieurs '' = doublons)."""
    Bailleur = apps.get_model('accounts', 'Bailleur')
    Bailleur.objects.filter(telephone='').update(telephone=None)
    Bailleur.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bailleur_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='deux_fa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(normaliser_identifiants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bailleur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('type_code', models.CharField(choices=[('2fa', 'Double authentification'), ('reset_password', 'Réinitialisation mot de passe')], max_length=20)),
                ('expire_at', models.DateTimeField()),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
