# Generated by Django 5.2.13 on 2026-06-15 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bailleur_deux_fa_active_alter_bailleur_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue_interface', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('fuseau_horaire', models.CharField(default='Africa/Douala', max_length=50)),
                ('format_date', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('theme', models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=10)),
                ('sons_notifications', models.BooleanField(default=True)),
                ('canal_rappel_prefere', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('appel', 'Appel vocal')], default='sms', max_length=20)),
                ('jours_avant_rappel', models.PositiveSmallIntegerField(default=3)),
                ('rappels_automatiques_actifs', models.BooleanField(default=True)),
                ('notifications_push_actives', models.BooleanField(default=True)),
                ('delai_grace_defaut', models.PositiveIntegerField(default=0)),
                ('type_penalite_defaut', models.CharField(choices=[('fixe', 'Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=20)),
                ('pourcentage_penalite_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
