# Generated by Django 5.2.13 on 2026-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configbailleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
