# Generated by Django 5.2.13 on 2026-04-28 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jour_echeance', models.IntegerField()),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('En discussion', 'En discussion'), ('En pénalité', 'En pénalité')], default='Payé', max_length=20)),
                ('date_entree', models.DateField()),
                ('penalite_journaliere', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_penalites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Appel', 'Appel Vocal')], max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Envoyé', 'Envoyé'), ('Echoué', 'Echoué')], max_length=10)),
                ('reponse_api', models.JSONField(blank=True, null=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='locataires.locataire')),
            ],
        ),
    ]
