# Generated by Django 5.2.8 on 2026-05-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='statut',
            field=models.CharField(choices=[('Payé', 'Payé'), ('En retard', 'En retard'), ('En discussion', 'En discussion'), ('En pénalité', 'En pénalité')], default='Payé', max_length=20),
        ),
    ]
