# Generated by Django 5.2.8 on 2026-05-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0002_alter_locataire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='logement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
