# Generated by Django 5.2.8 on 2026-05-18 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0003_locataire_logement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('type_notif', models.CharField(choices=[('paiement', 'Paiement'), ('retard', 'Retard'), ('penalite', 'Pénalité'), ('rappel', 'Rappel'), ('systeme', 'Système'), ('discussion', 'Discussion')], default='systeme', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
