# Generated by Django 5.2.8 on 2026-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='mode_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locataire',
            name='test_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
