# Generated by Django 5.2.13 on 2026-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0005_locataire_mode_test_locataire_test_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='signature_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
