# Generated by Django 5.2.13 on 2026-06-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
        ('locataires', '0006_locataire_signature_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='biens.unitelogement'),
        ),
    ]
