# Generated by Django 5.2.13 on 2026-06-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0008_migrer_logement_vers_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_debut_facturation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_fin_bail',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_versement_caution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='montant_caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='locataire',
            name='motif_sortie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='pieces_identite/'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='locataire',
            name='revenus_mensuels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='solde_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='locataire',
            name='statut_caution',
            field=models.CharField(choices=[('non_versee', 'Non versée'), ('versee', 'Versée'), ('restituee_totale', 'Restituée (totale)'), ('restituee_partielle', 'Restituée (partielle)'), ('conservee', 'Conservée')], default='non_versee', max_length=20),
        ),
        migrations.AddField(
            model_name='locataire',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('Passeport', 'Passeport'), ('Permis', 'Permis de conduire')], max_length=20),
        ),
        migrations.AddField(
            model_name='rappel',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rappel',
            name='message_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rappel',
            name='statut_livraison',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('signature_bailleur_base64', models.TextField(blank=True, null=True)),
                ('signature_locataire_base64', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('applique', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_loyers', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('versement', 'Versement'), ('restitution', 'Restitution'), ('deduction', 'Déduction')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caution', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoEtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='etats_des_lieux/')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locataires.etatdeslieux')),
            ],
        ),
    ]
