# Generated by Django 5.2.13 on 2026-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0009_locataire_archive_locataire_date_debut_facturation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='langue_preferee',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
    ]
