# Generated by Django 5.2.13 on 2026-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0010_locataire_langue_preferee'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='adresse_logement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locataire',
            name='charges_mensuelles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='locataire',
            name='duree_bail_mois',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='locataire',
            name='frequence_paiement',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
    ]
