# Generated by Django 5.2.13 on 2026-06-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0011_locataire_adresse_logement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceIdentiteFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces_identite/')),
                ('libelle', models.CharField(blank=True, max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_identite', to='locataires.locataire')),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]
