# Generated by Django 5.2.13 on 2026-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0012_pieceidentitefichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Payé', 'Payé'), ('En retard', 'En retard'), ('En discussion', 'En discussion'), ('En pénalité', 'En pénalité')], default='Nouveau', max_length=20),
        ),
    ]
