# Generated by Django 5.2.13 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Clôturée', 'Clôturée')], default='Active', max_length=10)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='locataires.locataire')),
            ],
        ),
    ]
