# Generated by Django 5.2.13 on 2026-06-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0006_locataire_signature_base64'),
        ('penalites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPenalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('delai_grace', models.IntegerField(default=0, help_text="Nombre de jours de tolérance après l'échéance avant pénalité")),
                ('type_penalite', models.CharField(choices=[('fixe', 'Montant fixe par jour'), ('pourcentage', 'Pourcentage du loyer par jour')], default='fixe', max_length=12)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Pénalité journalière en FCFA (si type=fixe)', max_digits=10, null=True)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage du loyer par jour de retard (si type=pourcentage)', max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='penalite',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AddField(
            model_name='penalite',
            name='date_derniere_application',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='date_remise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='penalite',
            name='motif_remise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='periode',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalite',
            name='statut',
            field=models.CharField(choices=[('Active', 'Active'), ('Clôturée', 'Clôturée'), ('Remise', 'Remise')], default='Active', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.UniqueConstraint(condition=models.Q(('periode__isnull', False)), fields=('locataire', 'periode'), name='unique_penalite_par_periode'),
        ),
        migrations.AddField(
            model_name='configpenalite',
            name='locataire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_penalite', to='locataires.locataire'),
        ),
    ]
