"""
Django settings for Loyatrack project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-ob6#$5#_=63id$78rnh1%te9qmf+4trx2pof61taj_1xa$hg^n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '127.0.0.1']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',

    # Local apps
    'accounts',
    'locataires',
    'paiements',
    'penalites',
    'biens',
    'comptabilite',
    'portail',
    'abonnements',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Loyatrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Loyatrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploads : pièces d'identité, photos d'état des lieux, documents PDF)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.Bailleur'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Swagger Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # For dev only. In prod, configure CORS_ALLOWED_ORIGINS

from celery.schedules import crontab

# Celery Settings
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_TIMEZONE = 'UTC'

CELERY_BEAT_SCHEDULE = {
    'verifier-echeances-tous-les-matins': {
        'task': 'locataires.tasks.verifier_echeances',
        'schedule': crontab(hour=9, minute=0),
    },
    'calculer-penalites-toutes-les-nuits': {
        'task': 'penalites.tasks.calculer_penalites',
        'schedule': crontab(hour=1, minute=0),
    },
    'appliquer-augmentations-loyer': {
        'task': 'locataires.tasks.appliquer_augmentations',
        'schedule': crontab(hour=2, minute=0),
    },
    'alerter-fin-de-bail': {
        'task': 'locataires.tasks.alerter_fin_bail',
        'schedule': crontab(hour=8, minute=0),
    },
    'sauvegarde-quotidienne': {
        'task': 'accounts.tasks.sauvegarder_donnees',
        'schedule': crontab(hour=3, minute=0),
    },
    'expirer-abonnements': {
        'task': 'abonnements.tasks.expirer_abonnements',
        'schedule': crontab(hour=0, minute=30),
    },
    'rappels-expiration-abonnement': {
        'task': 'abonnements.tasks.rappels_expiration',
        'schedule': crontab(hour=8, minute=30),
    },
}

# Abonnements — prestataire de paiement (agnostique). 'fake' en dev ; 'cinetpay' en prod.
PAIEMENT_PROVIDER = env('PAIEMENT_PROVIDER', default='fake')
# CinetPay (renseigner en prod via .env quand le compte marchand est prêt)
CINETPAY_API_KEY = env('CINETPAY_API_KEY', default='')
CINETPAY_SITE_ID = env('CINETPAY_SITE_ID', default='')
CINETPAY_SECRET_KEY = env('CINETPAY_SECRET_KEY', default='')
CINETPAY_NOTIFY_URL = env('CINETPAY_NOTIFY_URL', default='')
CINETPAY_RETURN_URL = env('CINETPAY_RETURN_URL', default='')

# Email Config (Mock/Console for now)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Twilio Config
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_NUMBER = env('TWILIO_NUMBER', default='')
TWILIO_WHATSAPP_NUMBER = env('TWILIO_WHATSAPP_NUMBER', default='')
