"""
Django settings for Loyatrack project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-ob6#$5#_=63id$78rnh1%te9qmf+4trx2pof61taj_1xa$hg^n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['10.0.2.2', 'localhost', '127.0.0.1'])
# Render fournit automatiquement le hostname public du service.
_RENDER_HOST = env('RENDER_EXTERNAL_HOSTNAME', default='')
if _RENDER_HOST:
    ALLOWED_HOSTS.append(_RENDER_HOST)

# Origines de confiance pour le CSRF (pages web : abonnement bailleur, admin).
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if _RENDER_HOST:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_RENDER_HOST}')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',

    # Local apps
    'accounts',
    'locataires',
    'paiements',
    'penalites',
    'biens',
    'comptabilite',
    'portail',
    'abonnements',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sert les fichiers statiques en prod
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Loyatrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Loyatrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL en prod via DATABASE_URL (Render) ; SQLite en local sinon.
if env('DATABASE_URL', default=''):
    DATABASES = {'default': env.db('DATABASE_URL')}
    DATABASES['default']['CONN_MAX_AGE'] = 600
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Stockage des statiques : WhiteNoise (CSS admin/Swagger servis en prod).
_STATIC_STORAGE = {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'}

# Médias (pièces d'identité, photos d'état des lieux) :
# - Cloudflare R2 (S3-compatible) en prod si R2_BUCKET est défini → uploads persistants.
# - Disque local sinon (dev). Firebase n'est PAS utilisé pour le stockage (push uniquement).
_R2_BUCKET = env('R2_BUCKET', default='')
if _R2_BUCKET:
    _media_options = {
        'bucket_name': _R2_BUCKET,
        'access_key': env('R2_ACCESS_KEY_ID', default=''),
        'secret_key': env('R2_SECRET_ACCESS_KEY', default=''),
        'endpoint_url': env('R2_ENDPOINT_URL', default=''),
        'region_name': 'auto',
        'signature_version': 's3v4',
        'querystring_auth': False,  # URLs publiques (bucket public R2)
        'default_acl': None,        # R2 ne gère pas les ACL S3
    }
    _r2_public = env('R2_PUBLIC_DOMAIN', default='')  # ex. pub-xxxx.r2.dev ou media.loyatrack.com
    if _r2_public:
        _media_options['custom_domain'] = _r2_public
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage', 'OPTIONS': _media_options},
        'staticfiles': _STATIC_STORAGE,
    }
else:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': _STATIC_STORAGE,
    }

# Media files (uploads : pièces d'identité, photos d'état des lieux, documents PDF)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.Bailleur'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Swagger Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# CORS : tout ouvert en dev ; restreint par liste blanche en prod.
# (L'app mobile utilise JWT sans cookies → CORS ne la concerne pas ; utile pour le web.)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

# Sécurité HTTPS activée uniquement en prod (DEBUG=False).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # derrière le proxy Render
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 2592000  # 30 jours
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

from celery.schedules import crontab

# Celery Settings
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_TIMEZONE = 'UTC'

CELERY_BEAT_SCHEDULE = {
    'verifier-echeances-tous-les-matins': {
        'task': 'locataires.tasks.verifier_echeances',
        'schedule': crontab(hour=9, minute=0),
    },
    'calculer-penalites-toutes-les-nuits': {
        'task': 'penalites.tasks.calculer_penalites',
        'schedule': crontab(hour=1, minute=0),
    },
    'appliquer-augmentations-loyer': {
        'task': 'locataires.tasks.appliquer_augmentations',
        'schedule': crontab(hour=2, minute=0),
    },
    'alerter-fin-de-bail': {
        'task': 'locataires.tasks.alerter_fin_bail',
        'schedule': crontab(hour=8, minute=0),
    },
    'sauvegarde-quotidienne': {
        'task': 'accounts.tasks.sauvegarder_donnees',
        'schedule': crontab(hour=3, minute=0),
    },
    'expirer-abonnements': {
        'task': 'abonnements.tasks.expirer_abonnements',
        'schedule': crontab(hour=0, minute=30),
    },
    'rappels-expiration-abonnement': {
        'task': 'abonnements.tasks.rappels_expiration',
        'schedule': crontab(hour=8, minute=30),
    },
}

# Abonnements — prestataire de paiement (agnostique). 'fake' en dev ; 'cinetpay' en prod.
PAIEMENT_PROVIDER = env('PAIEMENT_PROVIDER', default='fake')
# CinetPay (renseigner en prod via .env quand le compte marchand est prêt)
CINETPAY_API_KEY = env('CINETPAY_API_KEY', default='')
CINETPAY_SITE_ID = env('CINETPAY_SITE_ID', default='')
CINETPAY_SECRET_KEY = env('CINETPAY_SECRET_KEY', default='')
CINETPAY_NOTIFY_URL = env('CINETPAY_NOTIFY_URL', default='')
CINETPAY_RETURN_URL = env('CINETPAY_RETURN_URL', default='')

# Email Config (Mock/Console for now)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Twilio Config
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_NUMBER = env('TWILIO_NUMBER', default='')
TWILIO_WHATSAPP_NUMBER = env('TWILIO_WHATSAPP_NUMBER', default='')
