# Generated by Django 5.2.13 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Espèces', 'Espèces'), ('Virement', 'Virement')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='locataires.locataire')),
            ],
        ),
    ]
