# Generated by Django 5.2.13 on 2026-06-13 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement', '-id']},
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='nb_mois',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paiement',
            name='periode_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='periode_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reste_du',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('complet', 'Complet'), ('partiel', 'Partiel'), ('avance', 'Avance')], default='complet', max_length=10),
        ),
    ]
