# Generated by Django 5.2.13 on 2026-07-03 17:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0012_pieceidentitefichier'),
        ('paiements', '0002_alter_paiement_options_paiement_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteMarchand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestataire', models.CharField(default='cinetpay', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('site_id', models.CharField(blank=True, max_length=50)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('actif', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bailleur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_marchand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_loyer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periode', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('echouee', 'Échouée'), ('expiree', 'Expirée')], default='en_attente', max_length=12)),
                ('prestataire', models.CharField(default='cinetpay', max_length=20)),
                ('url_paiement', models.URLField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_paiement', to='locataires.locataire')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='paiements.paiement')),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
            },
        ),
    ]
