# Generated by Django 5.2.13 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_comptemarchand_demandepaiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptemarchand',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='comptemarchand',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='comptemarchand',
            name='site_id',
        ),
        migrations.AddField(
            model_name='comptemarchand',
            name='numero_momo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='comptemarchand',
            name='operateur',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money')], default='mtn', max_length=10),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='reversement_erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='reversement_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='reversement_statut',
            field=models.CharField(choices=[('non_requis', 'Non requis'), ('en_attente', 'En attente'), ('effectue', 'Effectué'), ('echoue', 'Échoué')], default='non_requis', max_length=12),
        ),
    ]
