# Generated by Django 5.2.13 on 2026-06-13 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('categorie', models.CharField(choices=[('entretien', 'Entretien / Réparation'), ('taxe', 'Taxe / Impôt'), ('charge', 'Charge (eau, électricité…)'), ('assurance', 'Assurance'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='biens.propriete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
