# Generated by Django 5.2.13 on 2026-06-13 23:05

import django.db.models.deletion
import portail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0009_locataire_archive_locataire_date_debut_facturation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=portail.models._token, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('locataire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acces_portail', to='locataires.locataire')),
            ],
        ),
    ]
