# Generated by Django 5.2.13 on 2026-06-13 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('immeuble', 'Immeuble'), ('autre', 'Autre')], default='immeuble', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='UniteLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('loyer_standard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('occupe', 'Occupé'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='biens.propriete')),
            ],
            options={
                'ordering': ['propriete', 'numero'],
            },
        ),
    ]
