# Generated by Django 5.2.13 on 2026-06-18 01:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], default='pro', max_length=12)),
                ('statut', models.CharField(choices=[('essai', 'Essai'), ('actif', 'Actif'), ('grace', 'Grâce'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='essai', max_length=10)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin_essai', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('periodicite', models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=10, null=True)),
                ('date_derniere_relance', models.DateField(blank=True, null=True)),
                ('bailleur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], max_length=12)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=8)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=12)),
                ('prestataire', models.CharField(default='fake', max_length=20)),
                ('reference_interne', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_externe', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_abonnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
