# Generated by Django 5.2.13 on 2026-06-18 08:25

import abonnements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_courtoisie_bailleurs_existants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JetonAccesBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=abonnements.models._token, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons_abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
