# Generated by Django 5.2.13 on 2026-07-10 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('chambre', 'Chambre'), ('immeuble', 'Immeuble'), ('bureau', 'Bureau'), ('autre', 'Autre')], default='appartement', max_length=20)),
                ('nb_chambres', models.PositiveSmallIntegerField(default=1)),
                ('nb_salons', models.PositiveSmallIntegerField(default=1)),
                ('nb_cuisines', models.PositiveSmallIntegerField(default=1)),
                ('nb_douches', models.PositiveSmallIntegerField(default=1)),
                ('superficie_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('meuble', models.BooleanField(default=False)),
                ('standing', models.CharField(blank=True, choices=[('economique', 'Économique'), ('moyen', 'Moyen standing'), ('haut', 'Haut standing')], max_length=12)),
                ('adresse_indicative', models.CharField(blank=True, max_length=255)),
                ('loyer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_mois', models.PositiveSmallIntegerField(default=1)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('disponible_le', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_moderation', 'En modération'), ('publiee', 'Publiée'), ('suspendue', 'Suspendue'), ('pourvue', 'Pourvue'), ('expiree', 'Expirée')], default='brouillon', max_length=14)),
                ('refus_motif', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_contacts', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='biens.unitelogement')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='annonces.quartier')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='annonces.ville')),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/%Y/%m/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('est_couverture', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quartier',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='annonces.ville'),
        ),
        migrations.AlterUniqueTogether(
            name='quartier',
            unique_together={('ville', 'slug')},
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['ville', 'quartier', 'type_bien', 'nb_chambres', 'statut'], name='annonces_an_ville_i_f1ebfc_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['statut', 'date_expiration'], name='annonces_an_statut_81f043_idx'),
        ),
    ]
