# Generated by Django 5.2.13 on 2026-07-10 23:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_ville'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('google_sub', models.CharField(blank=True, max_length=255)),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expire', models.DateTimeField(blank=True, null=True)),
                ('otp_tentatives', models.PositiveSmallIntegerField(default=0)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('archivee', 'Archivée'), ('bloquee', 'Bloquée')], default='ouverte', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(default=django.utils.timezone.now)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='annonces.annonce')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_annonces', to=settings.AUTH_USER_MODEL)),
                ('chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='annonces.chercheur')),
            ],
            options={
                'ordering': ['-date_dernier_message', '-id'],
                'unique_together': {('annonce', 'chercheur')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(choices=[('chercheur', 'Chercheur'), ('bailleur', 'Bailleur')], max_length=10)),
                ('corps', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='annonces.conversation')),
            ],
            options={
                'ordering': ['date_envoi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces.annonce')),
                ('chercheur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='annonces.chercheur')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces.conversation')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
